### ISSUE TITLE
java language client plugin doesn't work properly

### ISSUE THREAD

**Issue by magbulogtong81** [Acode-Foundation/Acode#1063]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

the jdtls in termux throws this error:

```SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:67)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
        at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$1(ParentProcessWatcher.java:144)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
        ... 12 more
Caused by: java.lang.IllegalArgumentException: URI has an authority component
        at java.base/sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:54)
        at java.base/sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:103)
        at java.base/java.nio.file.Path.of(Path.java:203)
        at java.base/java.nio.file.Paths.get(Paths.java:98)
        at org.eclipse.jdt.ls.core.internal.ResourceUtils.canonicalFilePathFromURI(ResourceUtils.java:230)
        at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.handleInitializationOptions(BaseInitHandler.java:100)
        at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:105)
        at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:64)
        at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:284)
        ... 17 more
```

live completion doesn't show subclasses
![Screenshot_20241029-071824](https://github.com/user-attachments/assets/adb4b095-541a-4e98-85d6-087759924b03)
![Screenshot_20241029-072347](https://github.com/user-attachments/assets/14a142d0-6e49-497f-a85d-71a3e439eb58)

how to reproduce:

- install java language client plugin in acode
- install acode language client & jdtls in termux, as instructed in the plugin
- run acode-lsp in termux
- open acode with java file opened

#### NOTE: I don't have the "copy device info" option on my command palette, I'll just manually put those things here
app version: 1.10.5 [playstore]
android version: android 11
webview version: version 129.0.6668.100

### If applicable, add mockups / screenshots regarding your vission

![Screenshot_20241029-070315](https://github.com/user-attachments/assets/5706a6af-dced-4a7e-8dad-aad2002b3c98)

![Screenshot_20241029-070417](https://github.com/user-attachments/assets/19de5227-1e04-497b-9157-12a664f7506a)

### If applicable, attach your Acode.log file to this issue.

<details><summary>Acode.log</summary><pre>
[2024-10-27T03:03:34.843Z] [INFO] Loading Settings...
[2024-10-27T03:03:35.117Z] [INFO] Loading language...
[2024-10-27T03:03:35.435Z] [INFO] App started!
[2024-10-27T03:14:04.225Z] [INFO] Loading Settings...
[2024-10-27T03:14:04.297Z] [INFO] Loading language...
[2024-10-27T03:14:04.527Z] [INFO] App started!
[2024-10-27T03:19:21.548Z] [INFO] Loading Settings...
[2024-10-27T03:19:21.618Z] [INFO] Loading language...
[2024-10-27T03:19:21.801Z] [INFO] App started!

**Comment by bajrangCoder** [comment]
This isn’t a bug with Acode; it’s related to the plugin itself.

I understand that Acode’s language client currently doesn’t provide the best LSP experience and could use a major update. The plugin developer has also mentioned plans to work on it, though he's busy at the moment. We're also working to improve the LSP experience, with some contributors already making progress. Hopefully, we'll see improvements soon!

In the meantime, you might try asking in the Telegram group—someone using the Java language client might be able to help.
